import 'dart:io';

import 'package:path/path.dart' as path;
import 'package:test/test.dart';
import 'package:zmodel_to_dart/zmodel_to_dart.dart';

void main() {
  test('generates enum and model output from zmodel source', () {
    const source = '''
enum role {
  admin
  reader
}

model user {
  id String @id
  name String
  role role
  createdAt DateTime
}
''';

    final generator = ZModelGenerator();
    final parsed = generator.parse(source);
    final output = generator.renderSingleLibrary(parsed);

    expect(output, contains('enum Role {'));
    expect(output, contains("admin('admin')"));
    expect(output, contains('class User {'));
    expect(output, contains('final String? id;'));
    expect(output, contains('final Role? role;'));
    expect(output, contains('final DateTime? createdAt;'));
    expect(
      output,
      contains('factory User.fromJson(Map<String, dynamic> json)'),
    );
    expect(output, contains("'createdAt': createdAt?.toIso8601String()"));
    expect(output, contains("'role': role?.toJson()"));
  });

  test('loads project config from zmodel_to_dart.yaml', () {
    final tempDir = Directory.systemTemp.createTempSync('zmodel_to_dart_test_');
    addTearDown(() => tempDir.deleteSync(recursive: true));

    final configFile = File(path.join(tempDir.path, 'zmodel_to_dart.yaml'));
    configFile.writeAsStringSync('''
input_globs:
  - schema/*.zmodel
output_suffix: .models.dart
output_dir: generated/dtos
banner: // GENERATED BY TEST
''');

    final config = ZModelToDartConfig.load(workingDirectory: tempDir.path);

    expect(config.inputGlobs, ['schema/*.zmodel']);
    expect(config.outputSuffix, '.models.dart');
    expect(config.outputDir, 'generated/dtos');
    expect(config.banner, '// GENERATED BY TEST');
    expect(config.matchesAssetPath('schema/app.zmodel'), isTrue);
    expect(config.matchesAssetPath('lib/app.zmodel'), isFalse);
  });

  test('merges inherited columns referenced by table directives', () {
    const source = '''
abstract model base_model {
  UUID String
}

model tb_parameter extends base_model {
  PARAMETER_ID Int @id
  @@unique([UUID, PARAMETER_ID])
}
''';

    final generator = ZModelGenerator();
    final parsed = generator.parse(source);
    final output = generator.renderSingleLibrary(parsed);

    expect(RegExp(r'final String\? uuid;').allMatches(output).length, 1);
    expect(RegExp(r'required this\.uuid').allMatches(output), isEmpty);
    expect(output.split("uuid: json['UUID']").length - 1, 1);
    expect(output.split("'UUID': uuid").length - 1, 1);
  });
}
