import 'dart:io';

import 'package:path/path.dart' as path;
import 'package:test/test.dart';
import 'package:zmodel_to_dart/zmodel_to_dart.dart';

void main() {
  test('generates enum and model output from zmodel source', () {
    const source = '''
enum role {
  admin
  reader
}

model user {
  id String @id
  name String
  role role
  createdAt DateTime
}
''';

    final generator = ZModelGenerator();
    final parsed = generator.parse(source);
    final output = generator.renderSingleLibrary(parsed);

    expect(output, contains('abstract class ZModel {'));
    expect(output, contains("case const (User): return 'user';"));
    expect(
      output,
      contains('case const (User): return User.fromJson(json) as T;'),
    );
    expect(output, contains('enum Role {'));
    expect(output, contains("admin('admin')"));
    expect(output, contains('class User extends ZModel {'));
    expect(output, contains('final String? id;'));
    expect(output, contains('final Role? role;'));
    expect(output, contains('final DateTime? createdAt;'));
    expect(
      output,
      contains('factory User.fromJson(Map<String, dynamic> json)'),
    );
    expect(output, contains("'createdAt': createdAt?.toIso8601String()"));
    expect(output, contains("'role': role?.toJson()"));
  });

  test('loads project config from zmodel_to_dart.yaml', () {
    final tempDir = Directory.systemTemp.createTempSync('zmodel_to_dart_test_');
    addTearDown(() => tempDir.deleteSync(recursive: true));

    final configFile = File(path.join(tempDir.path, 'zmodel_to_dart.yaml'));
    configFile.writeAsStringSync('''
input_globs:
  - schema/*.zmodel
output_suffix: .models.dart
output_dir: generated/dtos
banner: // GENERATED BY TEST
''');

    final config = ZModelToDartConfig.load(workingDirectory: tempDir.path);

    expect(config.inputGlobs, ['schema/*.zmodel']);
    expect(config.outputSuffix, '.models.dart');
    expect(config.outputDir, 'generated/dtos');
    expect(config.banner, '// GENERATED BY TEST');
    expect(config.matchesAssetPath('schema/app.zmodel'), isTrue);
    expect(config.matchesAssetPath('lib/app.zmodel'), isFalse);
  });

  test('merges inherited columns referenced by table directives', () {
    const source = '''
abstract model base_model {
  UUID String
}

model tb_parameter extends base_model {
  PARAMETER_ID Int @id
  @@unique([UUID, PARAMETER_ID])
}
''';

    final generator = ZModelGenerator();
    final parsed = generator.parse(source);
    final output = generator.renderSingleLibrary(parsed);

    expect(RegExp(r'final String\? uuid;').allMatches(output).length, 1);
    expect(RegExp(r'required this\.uuid').allMatches(output), isEmpty);
    expect(output.split("uuid: json['UUID']").length - 1, 1);
    expect(output.split("'UUID': uuid").length - 1, 1);
  });

  test('loads rpc config from zmodel_to_dart.yaml', () {
    final tempDir = Directory.systemTemp.createTempSync('zmodel_to_dart_test_');
    addTearDown(() => tempDir.deleteSync(recursive: true));

    final configFile = File(path.join(tempDir.path, 'zmodel_to_dart.yaml'));
    configFile.writeAsStringSync('''
generate_rpc_clients: true
rpc_base_path: /api/rpc/model
''');

    final config = ZModelToDartConfig.load(workingDirectory: tempDir.path);

    expect(config.generateRpcClients, isTrue);
    expect(config.rpcBasePath, '/api/rpc/model');
  });

  test('generates a generic rpc client with direct method parameters', () {
    const source = '''
model user {
  id String @id
  name String
}
''';

    final generator = ZModelGenerator();
    final parsed = generator.parse(source);
    final output = generator.renderSingleLibrary(
      parsed,
      includeRpcClients: true,
      rpcBasePath: '/api/rpc/model',
    );

    expect(output, contains('enum ZenStackRpcMethod { get, post }'));
    expect(output, contains('abstract interface class ZenStackRpcTransport {'));
    expect(output, contains('class ZModelRpcClient {'));
    expect(
      output,
      contains(
        'Future<List<T>> findMany<T extends ZModel>({Map<String, dynamic>? where, Map<String, dynamic>? select, Map<String, dynamic>? include, List<Map<String, String>>? orderBy, int? take, int? skip, Map<String, dynamic>? meta}) async {',
      ),
    );
    expect(
      output,
      contains(
        r"String _path<T extends ZModel>(String operation) => '$basePath/${ZModel.modelNameOf<T>()}/$operation';",
      ),
    );
    expect(output, contains('Map<String, String>? _queryParameters({'));
    expect(output, contains("_path<T>('findMany')"));
    expect(output, contains('return ZModel.listFromJson<T>(items);'));
    expect(
      output,
      contains('return ZModel.fromJson<T>(response as Map<String, dynamic>);'),
    );
    expect(
      output,
      contains("final params = <String, String>{'q': jsonEncode(payload)};"),
    );
    expect(output, contains("'data': data.toJson()"));
    expect(output, contains("'where': where"));
  });
}
